name: prod-payos-gohighlevel
on:
  push:
    branches:
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: |
            cd applications/ghl-payos-api
            yarn install
            yarn build
            zip -r build.zip dist package.json package-lock.json
            ls -la

      - name: Copy file via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          source: "./applications/ghl-payos-api/build.zip"
          target: "/var/www/ghl_payos/applications/test"
          strip_components: 2

      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd /var/www/ghl_payos/applications/test/ghl-payos-api
            unzip -o build.zip


        
