name: prod-payos-gohighlevel
on:
  push:
    branches:
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: move to app
        run: cd applications/ghl-payos-api

      - name: build
        run: yarn install && yarn run build

      - name: Zip build
        run: zip -r build.zip dist package.json package-lock.json

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy file via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          source: "build.zip"
          target: /var/www/ghl_payos/applications
        
